### ISSUE TITLE
error: input 'dream2nix/all-cabal-json' follows a non-existent input 'nci'

### ISSUE THREAD

**Issue by Philipp-M** [yusdacra/nix-cargo-integration#120]
A collegue of mine tried to use helix as flake input and nix had this issue:

```
error: input 'helix/nci/dream2nix/all-cabal-json' follows a non-existent input 'nci'
```

Could it be that https://github.com/yusdacra/nix-cargo-integration/blob/fc5c8ac103cf3f8ca32bf53e70e3558115a07118/flake.nix#L27

following empty strings can result in this issue, why is this (and the other `follows` there) empty anyways?
I for some reason don't have the issue, with the same flake input, but I'm on NixOS, while my collegue is using Nix on PopOS!.

**Comment by yusdacra** [comment]
> why is this (and the other follows there) empty anyways?

This is because we don't use these inputs of dream2nix, they are for other languages support. So we set them to empty string (which makes nix point it to self) so that they don't get fetched for no reason.

> while my collegue is using Nix on PopOS!.

What Nix version are they using? I am not sure why this issue would happen as it doesn't happen for me either (but I also use NixOS).

**Comment by Philipp-M** [comment]
Indeed an ancient version of Nix was the issue, thanks for suggesting this.
