### ISSUE TITLE
`outputs.apps.${system}` empty even tho `nix run .#<bin>` works

### ISSUE THREAD

**Issue by quinn-dougherty** [yusdacra/nix-cargo-integration#148]
in [this](https://github.com/cspr-rad/ltl-actus/blob/master/nix/crates/default.nix) `crates.nix` and flake: 
```sh
qd@grindenstern ~/p/c/ltl-actus (master)> nix repl
Welcome to Nix 2.19.2. Type :? for help.

nix-repl> :lf .
warning: Git tree '/home/qd/projects/casper/ltl-actus' is dirty
Added 20 variables.

nix-repl> apps.x86_64-linux
{ }
```

However, 

```sh
nix run .#ltl_actus_cli-release -- exec --path ./tests/examples/loan-1.toml
```
works. 

When I try `apps.default = config.nci.crates.cli;` or the like in `perSystem`, (so i could just do `nix run -- ...`), I get: 
```sh
error: The option `perSystem.x86_64-linux.apps.default.checkProfile' does not exist. Definition values:
       - In `/nix/store/1jd7lkip20mkwn490zrynildrbqp6zy0-source/nix/crates, via option perSystem': "release"
```

alluding to https://github.com/yusdacra/nix-cargo-integration/issues/147

**Comment by yusdacra** [comment]
`nci` doesn't output any app outputs (right now anyway, I haven't re-implemented using `bin` entries in `Cargo.toml` to generate app outputs). The `nix run` only works because Nix has a builtin behaviour where it will try to run a `package` output if it doesn't exist as an `app`.

`config.nci.crates.cli` isn't the output itself, it's just the configuration for a crate, so you don't want to set that to anywhere, so the error doesn't matter. The way you would set an app would look like this:
```
    apps.default.program = "${config.nci.outputs.ltl_actus_cli.packages.release}/bin/cli";
```

BTW, looking further at your Nix code, you'll want to make sure that the crates you are configuring match the names in their respective `Cargo.toml`. So instead of setting `cli = import ./cli.nix { inherit pkgs config; };` you'd want to set `ltl_actus_cli = import ./cli.nix { inherit pkgs config; };`.
