### ISSUE TITLE
use crate2nix from nixpkgs ?

### ISSUE THREAD

**Issue by happysalada** [yusdacra/nix-cargo-integration#38]
First of all, thank you for the software!

Just a small problem I've been running on. When using a flake that uses nix-cargo-integration (I use helix for example). When I need to build the system, it uses a custom version of crate2nix that needs to be rebuilt everytime. That crate2nix version downloads and builds  300 rust crates. If I run the garbage collectors, those crates are deleted, and need to be redownloaded and built, which is a littlle unintuitive.

I'm not sure what the best solution for this is. I think crate2nix is pretty stable, but I understand your concern of using a specific version.

**Comment by yusdacra** [comment]
For `nix-cargo-integration` to be able to use the crate2nix from nixpkgs, a few stuff needs to be done:

1. Make it so that the `tools.nix` in crate2nix takes a `crate2nix` attribute that overrides what crate2nix package to use (it currently will just use the generated Cargo.nix in it's repository to build, https://github.com/kolloch/crate2nix/blob/master/tools.nix#L15).
2. `nix-cargo-integration` should expose a boolean option to set the said attribute to `rustPkgs.crate2nix` (the import https://github.com/yusdacra/nix-cargo-integration/blob/master/src/nixpkgs.nix#L70 here will need to set `crate2nix = rustPkgs.crate2nix;`).

These should be enough to make it use the crate2nix from nixpkgs. I will try implementing this today or tomorrow.

**Comment by happysalada** [comment]
No rush at all, thank you for having a look!

**Comment by yusdacra** [comment]
I created the `feat/crate2nix-pkgs` branch where the above is implemented, it would be good if you could give it a try. To use the crate2nix package from nixpkgs, you need to pass `useCrate2NixFromPkgs = true;` to `makeOutputs`.

**Comment by happysalada** [comment]
Just tested. Here is what I did.
modified my local copy of helix to use the `feat/crate2nix-pkgs`, then added the `useCrate2nixFromPkgs = true`.
nix flake update my system. I was a little surprised in that it tried to build another version of crate2nix. But after I switched and garbage collected, a rebuild is instantaneous, no need to rebuild crate2nix again.
So LGTM, thank you for taking care of that so fast!

**Comment by yusdacra** [comment]
That's good to hear! I will merge the branch to master after I take care of documentation then.

**Comment by happysalada** [comment]
Sorry I spoke too fast. I tested again this morning and it's still rebuilding a custom crate2nix.
I added a package to my configuration (an unrelated one and that triggered a full re-evaluation). Probably the first time I tested the evaluation was cached.
Sorry for not spotting this earlier.

**Comment by yusdacra** [comment]
Can you confirm it's building the package from it's repository? If it's building many derivations seperately still then that could mean something else is triggering it? Trying it with a simple flake would be a good idea to see if it actually uses the nixpkgs package.

**Comment by happysalada** [comment]
Let me try to integrate nix-cargo-integration into a small rust repo I'm using, it should be easier to verify.
It's definitely building 2 different versions of crate2nix but for the love of me I can't figure out why.

**Comment by yusdacra** [comment]
I'm not sure why it would be using multiple versions... The boolean flag is used while importing the nixpkgs package set, which means it should be applied globally to everything that `nix-cargo-integration` does. But trying with a simple repository might be helpful for debugging.

**Comment by happysalada** [comment]
I've tracked the dependency, it's inside nixpkgs.nix
https://github.com/happysalada/nix-cargo-integration/commit/5cf4139a1b45b5ac4d2e4754d16f9367d45df5ba
in my commit I've removed the crate2nix external dependency completely just to see where it would fail. Feel free to keep yours, you just need the conditional to not use sources.crate2nix.
let me know if anything.

**Comment by happysalada** [comment]
That won't work though, since the nixpkgs crate2nix doesn't ship a tools.nix.

**Comment by yusdacra** [comment]
Oh I totally did not notice that... I thought only replacing the crate2nix package that `tools.nix` uses would be enough, but guess not...

Also, if you don't mind, we could put that repo in examples :D

**Comment by yusdacra** [comment]
Ah yeah i do change the rust toolchain used, that will be a factor. To workaround that i can make it so that crate2nix package is taken from the original package set if the conditional is enabled.

About tests, i believe you need to do it like here https://gitlab.com/veloren/veloren/-/blob/master/flake.nix#L22 for crate2nix.

As for modifying the flake outputs, there isn't a dedicated override yet for that, but i will add it since it comes quite handy. `makeOutputs` simply outputs flake outputs so you could override that (one of the examples has that iirc)

**Comment by happysalada** [comment]
Thank you for the disabling the tests, it woked like a charm. Right now I am adding the module to the outputs by merging. Happy to change if/when there is a better way.

**Comment by yusdacra** [comment]
Closing this since i intend to drop crate2nix in favor of #49 once it is done.
